# Generated by Django 4.1.7 on 2023-06-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfirst', '0002_album_country_album_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('pic', models.ImageField(upload_to='pic')),
                ('disc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='album',
            name='country',
        ),
        migrations.RemoveField(
            model_name='album',
            name='price',
        ),
    ]
